// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsOAgvOyd09BFRGlJl2up_OXeto3OGJCM',
    appId: '1:665112773024:web:546e7a42b1bc08b01564c5',
    messagingSenderId: '665112773024',
    projectId: 'wesalapp-49534',
    authDomain: 'wesalapp-49534.firebaseapp.com',
    storageBucket: 'wesalapp-49534.firebasestorage.app',
    measurementId: 'G-LR72MZTJ7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB--anLLiiGhXQFVBK2riqgtsJRRiFHJUk',
    appId: '1:665112773024:android:8493a2dc8718505d1564c5',
    messagingSenderId: '665112773024',
    projectId: 'wesalapp-49534',
    storageBucket: 'wesalapp-49534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb3G_2zW2nXaX6K8qpuhV1pwYA6p9gigM',
    appId: '1:665112773024:ios:b032ee73ca1bfa091564c5',
    messagingSenderId: '665112773024',
    projectId: 'wesalapp-49534',
    storageBucket: 'wesalapp-49534.firebasestorage.app',
    iosBundleId: 'com.example.wesalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb3G_2zW2nXaX6K8qpuhV1pwYA6p9gigM',
    appId: '1:665112773024:ios:b032ee73ca1bfa091564c5',
    messagingSenderId: '665112773024',
    projectId: 'wesalapp-49534',
    storageBucket: 'wesalapp-49534.firebasestorage.app',
    iosBundleId: 'com.example.wesalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsOAgvOyd09BFRGlJl2up_OXeto3OGJCM',
    appId: '1:665112773024:web:045c802023dc43581564c5',
    messagingSenderId: '665112773024',
    projectId: 'wesalapp-49534',
    authDomain: 'wesalapp-49534.firebaseapp.com',
    storageBucket: 'wesalapp-49534.firebasestorage.app',
    measurementId: 'G-WDK3FJLWQ5',
  );
}
